-- Add to naval units the "Open Water" ability
-- Melee naval units
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_GALLEY',						'CLASS_NAVAL_MELEE'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_MELEE');
			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_CARAVEL',						'CLASS_NAVAL_MELEE'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_MELEE');
			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_IRONCLAD',						'CLASS_NAVAL_MELEE'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_MELEE');			

INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_DESTROYER',						'CLASS_NAVAL_MELEE'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_MELEE');			
-- Ranged naval units			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_QUADRIREME',						'CLASS_NAVAL_RANGED'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RANGED');
			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_FRIGATE',						'CLASS_NAVAL_RANGED'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RANGED');
			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_BATTLESHIP',						'CLASS_NAVAL_RANGED'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RANGED');			

INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_MISSILE_CRUISER',						'CLASS_NAVAL_RANGED'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RANGED');				
-- Raid naval units			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_PRIVATEER',						'CLASS_NAVAL_RAIDER'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RAIDER');
			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_SUBMARINE',						'CLASS_NAVAL_RAIDER'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RAIDER');
			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_NUCLEAR_SUBMARINE',						'CLASS_NAVAL_RAIDER'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RAIDER');			
-- Aircraft carrier						
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_AIRCRAFT_CARRIER',						'CLASS_NAVAL_CARRIER'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_CARRIER');	
--Unique and DLC ships
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_DE_ZEVEN_PROVINCIEN',						'CLASS_NAVAL_RANGED'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RANGED');	
			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_NORWEGIAN_LONGSHIP',						'CLASS_LONGSHIP'),
			('ABILITY_OPEN_WATER',	'CLASS_LONGSHIP');			
			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_ENGLISH_SEADOG',						'CLASS_NAVAL_RAIDER'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RAIDER');	

INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_GERMAN_UBOAT',						'CLASS_UBOAT'),
			('ABILITY_OPEN_WATER',	'CLASS_UBOAT');	
			
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_BRAZILIAN_MINAS_GERAES',						'CLASS_NAVAL_RANGED'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RANGED');	

INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_OTTOMAN_BARBARY_CORSAIR',						'CLASS_CORSAIR'),
			('ABILITY_OPEN_WATER',	'CLASS_CORSAIR');				
		
INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_PHOENICIA_BIREME',						'CLASS_BIREME'),
			('ABILITY_OPEN_WATER',	'CLASS_BIREME');	

INSERT OR REPLACE INTO TypeTags
			(Type,										Tag)
VALUES		('UNIT_INDONESIAN_JONG',						'CLASS_NAVAL_RANGED'),
			('ABILITY_OPEN_WATER',	'CLASS_NAVAL_RANGED');			
-- the "Open Water" ability code
INSERT INTO Types	
		(Type,										Kind)
VALUES	('ABILITY_OPEN_WATER',					'KIND_ABILITY');

INSERT INTO UnitAbilities			
		(UnitAbilityType,							Name,									Description)
VALUES	('ABILITY_OPEN_WATER',					"LOC_ABILITY_ARCHAEOLOGIST_ENTER_FOREIGN_LANDS_NAME",		"LOC_ABILITY_ARCHAEOLOGIST_ENTER_FOREIGN_LANDS_DESCRIPTION");

INSERT INTO UnitAbilityModifiers	
		(UnitAbilityType,									ModifierId)
VALUES	('ABILITY_OPEN_WATER',							'MOD_ENTER_FOREIGN_LANDS');